name = "go-toolkit-docs"
main = "workers-site/index.min.js"
compatibility_date = "2026-01-03"
compatibility_flags = ["nodejs_compat"]

routes = [
    { pattern = "valksor.com/docs/go-toolkit", zone_name = "valksor.com" },
    { pattern = "valksor.com/docs/go-toolkit/*", zone_name = "valksor.com" }
]

[site]
bucket = "./docs"
